In [1]:
import os

https://blog.dask.org/2019/03/18/dask-nep18

In [2]:
import numpy as np
import dask
import dask.array

print(np.__version__)
print(dask.__version__)

1.16.3
1.2.0


In [3]:
# This only works if you have a NVIDIA GPU with CUDA support
import cupy

print(cupy.__version__)

6.0.0rc1


In [33]:
import numpy as np
import dask.array


x = np.random.random((5000, 1000))
q, r = np.linalg.qr(x)
type(r)

numpy.ndarray

In [34]:
d = dask.array.from_array(x, chunks=(1000, 1000))
q, r = np.linalg.qr(d)
type(r)

dask.array.core.Array

In [5]:
import numpy as np
import cupy
import dask.array as da

x = np.random.random((1000, 100))
y = cupy.array(x)

dx = da.from_array(x, chunks=(500, 100))
dy = da.from_array(y, chunks=(500, 100), asarray=False)


In [6]:
u, s, v = np.linalg.svd(x)


In [7]:
type(y)

cupy.core.core.ndarray

In [8]:
u, s, v = np.linalg.svd(y)

In [9]:
ye = np.exp(y)
type(ye)

cupy.core.core.ndarray

In [20]:
x = np.random.random((5000, 500))
y = cupy.array(x)


%timeit np.exp(x)

616 µs ± 37.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [21]:
%timeit np.exp(y)

348 µs ± 2.29 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [22]:
%timeit cupy.exp(y)

353 µs ± 18 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [30]:
import numpy as np
import cupy


def do_something_useful(x):
    return np.log(np.sin(x) + 5)


x = np.random.random((10000, 1000))

In [31]:
%timeit do_something_useful(x)

21.3 ms ± 363 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [32]:
y = cupy.array(x)

%timeit do_something_useful(y)

4.66 ms ± 28.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [38]:
import numpy as np
import cupy


def do_something_useful(x):
    with np.errstate(invalid='raise'):
        result = np.log(np.sin(x) + 5)

    return result


x = np.random.random((10000, 1000))
x[0, 1] = np.nan
do_something_useful(x)

FloatingPointError: invalid value encountered in sin

In [41]:
y = cupy.array(x)
y[:2, :3]

array([[0.65229834,        nan, 0.15399398],
       [0.45149177, 0.60147911, 0.80325624]])

In [40]:
y[:2, :3]

array([[0.65229834,        nan, 0.15399398],
       [0.45149177, 0.60147911, 0.80325624]])

In [42]:
do_something_useful(y)

array([[1.7240184 ,        nan, 1.63965399, ..., 1.70828799, 1.70032669,
        1.73915025],
       [1.69310021, 1.71665198, 1.74390253, ..., 1.74861999, 1.75095169,
        1.67298366],
       [1.76261031, 1.6114697 , 1.61174371, ..., 1.64817023, 1.72002804,
        1.68450369],
       ...,
       [1.66128411, 1.71233827, 1.72747532, ..., 1.72319951, 1.67996323,
        1.75232611],
       [1.63691778, 1.76158719, 1.61184249, ..., 1.73941184, 1.63515588,
        1.70605217],
       [1.69984733, 1.71771392, 1.67277521, ..., 1.71641843, 1.70031704,
        1.6602814 ]])

In [44]:
import unumpy as np

In [48]:
np.sin(3)

BackendNotImplementedError: No selected backends had an implementation for this method.

In [49]:
np.array??

Signature:       np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
Call signature:  np.array(*args, **kwargs)
Type:            MultiMethod
String form:     <function array at 0x7fb944753f28>
File:            ~/anaconda3/envs/pydata-ams/lib/python3.7/site-packages/uarray/backend.py
Source:         
class MultiMethod:
    """
    This class is meant to provide a dispatchable method with or without a registered implementation.

    Provides a multi-method instance. The method has no implementation by default, but one can be provided
    if needed. :obj:`Backend` s can provide implementations for the method, and users can choose backends.

    Parameters
    ----------
    argument_extractor : ArgumentExtractorType
        This is a callable that extracts the arguments over which the dispatch will be performed.
    argument_replacer : ArgumentReplacerType
        This takes in args, kwargs and dispatchable args, and replaces all dispatchable arguments within
        

In [50]:
dir(np)

['DispatchableInstance',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute',
 'add',
 'all',
 'all_of_type',
 'any',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'array',
 'asarray',
 'bitwise_and',
 'bitwise_or',
 'bitwise_xor',
 'cbrt',
 'ceil',
 'conj',
 'copysign',
 'cos',
 'cosh',
 'create_multimethod',
 'deg2rad',
 'divide',
 'divmod',
 'equal',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'floor',
 'floor_divide',
 'fmax',
 'fmin',
 'fmod',
 'frexp',
 'gcd',
 'greater',
 'greater_equal',
 'heaviside',
 'hypot',
 'in1d',
 'intersect1d',
 'invert',
 'isfinite',
 'isin',
 'isinf',
 'isnan',
 'isnat',
 'lcm',
 'ldexp',
 'left_shift',
 'less',
 'less_equal',
 'lexsort',
 'log',
 'log10',
 'log1p',
 'log2',
 'logaddexp',
 'logaddexp2',
 'logical_and',
 'logical_not',
 'logical_or',
 'logical_xor',
 'max',
 'maximum',
 'min',
 'minimum',


In [78]:
import uarray
import unumpy as np

with uarray.set_backend('numpy'):
    x = np.arange(10)

AttributeError: 'str' object has no attribute 'try_backend'

In [73]:
with uarray.set_backend(uarray.NumPyBackend):
    x = np.arange(10)

AttributeError: module 'uarray' has no attribute 'NumPyBackend'

In [65]:
import unumpy

In [68]:
np.arange(100)

BackendNotImplementedError: No selected backends had an implementation for this method.

In [1]:
import uarray
import unumpy as np
from unumpy.numpy_backend import NumpyBackend

x1 = np.arange(10)

In [2]:
from unumpy.xnd_backend import XndBackend

# Now that we have 2 backends, need to specify which one to use
with uarray.set_backend(XndBackend):    
    x2 = np.ones(10)
    
print(type(x1))
print(type(x2))

<class 'numpy.ndarray'>
<class 'xnd.array'>


In [3]:
x1 + x2  # coerces numpy array to XND array

array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, ...], type='10 * float64')

In [4]:
from unumpy.torch_backend import TorchBackend

with uarray.set_backend(TorchBackend):
    x3 = np.arange(0., 20, 2)
    
print(type(x3), x3.dtype)
np.sin(x3)

<class 'torch.Tensor'> torch.float32


tensor([ 0.0000,  0.9093, -0.7568, -0.2794,  0.9894, -0.5440, -0.5366,  0.9906,
        -0.2879, -0.7510])

In [105]:
# This looks off ...


with uarray.set_backend(TorchBackend):
    y = np.sin(x1)
    print(type(y))
    
    with uarray.skip_backend(NumpyBackend):
        y2 = np.sin(x1)
        print(type(y2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
